- hosts: localhost
  tasks:
  - name: get current logged in user
    shell: users
    register: user

- hosts: localhost
  become: true
  become_user: "{{ user | replace('\n', '') | replace(' ', '') }}"
  tasks:
  # LINK DOTFILES
  - name: Clone dotfiles
    git:
      dest: ~/.dotfiles
      repo: git@github.com:kevintpeng/dotfiles.git
      update: yes
  - name: link .vimrc
    file: 
      src: ~/.dotfiles/.vimrc
      dest: ~/.vimrc
      state: hard
  - name: link .zshrc
    file: 
      src: ~/.dotfiles/.zshrc
      dest: ~/.zshrc
      state: hard
  - name: link .tmux.conf
    file: 
      src: ~/.dotfiles/.tmux.conf
      dest: ~/.tmux.conf
      state: hard
  - name: link .chunkwmrc
    file: 
      src: ~/.dotfiles/.chunkwmrc
      dest: ~/.chunkwmrc
      state: hard
  - name: link .skhdrc
    file: 
      src: ~/.dotfiles/.skhdrc
      dest: ~/.skhdrc
      state: hard
  - name: link .mackup.cfg
    file: 
      src: ~/.dotfiles/.mackup.cfg
      dest: ~/.mackup.cfg
      state: hard

  # ASTHETIC
  #- name: Tap Hack Nerd Font
  #  homebrew_tap:
  #    name: caskroom/fonts
  #    state: present
  - name: install hack-nerd-font
    homebrew_cask:
      pkg: font-hack-nerd-font
      state: present
  - name: Install base16 colorscheme
    git:
      repo: https://github.com/chriskempson/base16-shell.git
      dest: ~/.config/base16-shell
      update: yes
  #- name: Set terminal colorscheme to default-dark
  #  shell: base16_default-dark

  # WINDOW MANAGER
  - name: Tap chunkwm 
    homebrew_tap:
      name: crisidev/homebrew-chunkwm
      state: present
  - name: Install chunkwm
    homebrew:
      name: chunkwm
      state: present
  - name: Install skhd
    homebrew:
      pkg: koekeishiya/formulae/skhd
      state: present
      options: HEAD,with-logging
  - name: Check existence
    stat:
      path: /usr/local/bin/qes
    register: qes
  - name: Pull qes
    git:
      repo: https://github.com/koekeishiya/qes.git
      dest: /usr/local/etc/qes
      update: yes
    when: qes.stat.exists == False
  - name: Build qes
    shell: make
    args:
      chdir: /usr/local/etc/qes
    when: qes.stat.exists == False
  - name: Add qes to path
    file:
      src: /usr/local/etc/qes/bin/qes
      dest: /usr/local/bin/qes
      state: hard
    when: qes.stat.exists == False

  # UTILITIES
  - name: Install pure prompt
    npm:
      name: pure-prompt
      global: yes
      state: latest
  - name: Install tree
    homebrew:
      name: tree
      state: present
  - name: Install fzf
    homebrew:
      name: fzf
      state: present
  - name: Configure fzf with useful key bindings and fuzzy completion
    shell: $(brew --prefix)/opt/fzf/install
  - name: Install tmux
    homebrew:
      name: tmux
      state: present
  - name: Install iTerm2
    homebrew_cask:
      pkg: iterm2
      state: present
  - name: Install vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim
      update: yes
  - name: Install all vim plugins
    shell: vim +PluginInstall +qall
  - name: Install opr and ogh
    gem:
      name: open_git
      state: present
  - name: Install Mackup
    homebrew:
      pkg: mackup
      state: present
  - name: Mackup backup
    shell: mackup backup

  # APPS
  - name: Install Google Chrome
    homebrew_cask:
      pkg: google-chrome
      state: present
    ignore_errors: True
  - name: Install Anki
    homebrew_cask:
      pkg: anki
      state: present
    ignore_errors: True
  - name: Install Steam
    homebrew_cask:
      pkg: steam
      state: present
    ignore_errors: True
  - name: Install Discord
    homebrew_cask:
      pkg: discord
      state: present
    ignore_errors: True
  - name: Install 1Password
    homebrew_cask:
      pkg: 1password
      state: present
    ignore_errors: True
  - name: Install Karabiner-Elements
    homebrew_cask:
      pkg: karabiner-elements
      state: present
    ignore_errors: True
  - name: Install flux
    homebrew_cask:
      pkg: flux
      state: present
    ignore_errors: True
  - name: Install Deluge
    homebrew_cask:
      pkg: deluge
      state: present
    ignore_errors: True
