- hosts: localhost
  become: true
  become_user: kevintpeng
  tasks:
  # LINK DOTFILES
  - name: link .vimrc
    file: 
      dest: .vimrc
      src: ~/.vimrc
      state: link
  - name: link .zshrc
    file: 
      dest: .zshrc
      src: ~/.zshrc
      state: link
  - name: link .tmux.conf
    file: 
      dest: .tmux.conf
      src: ~/.tmux.conf
      state: link
  - name: link .chunkwmrc
    file: 
      dest: .chunkwmrc
      src: ~/.chunkwrc
      state: link
  - name: link .skhdrc
    file: 
      dest: .skhdrc
      src: ~/.skhdrc
      state: link

  # UTILITIES
  - name: Install tree
    homebrew:
      name: tree
      state: present
  - name: Install fzf
    homebrew:
      name: fzf
      state: present
  - name: Configure fzf with useful key bindings and fuzzy completion
    shell: $(brew --prefix)/opt/fzf/install
  - name: Install tmux
    homebrew:
      name: tmux
      state: present
  - name: Install iTerm2
    homebrew_cask:
      pkg: iterm2
      state: present
  - name: Install vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim
      update: yes
  - name: Install all vim plugins
    shell: vim +PluginInstall +qall

  # ASTHETIC
  #- name: Tap Hack Nerd Font
  #  homebrew_tap:
  #    name: caskroom/fonts
  #    state: present
  - name: install hack-nerd-font
    homebrew_cask:
      pkg: font-hack-nerd-font
      state: present

  # WINDOW MANAGER
  - name: Tap chunkwm 
    homebrew_tap:
      name: crisidev/homebrew-chunkwm
      state: present
  - name: Install chunkwm
    homebrew:
      name: chunkwm
      state: present
  - name: Install skhd
    homebrew:
      pkg: koekeishiya/formulae/skhd
      state: present
      options: HEAD,with-logging
  - name: Install chunkwm
    homebrew_cask:
      pkg: chunkwm
      state: present

