- hosts: localhost
  become: true
  become_user: "{{ username }}"
  tasks:
  - name: Install Dotfiles
    include: ./ansible/dotfiles.yml
    tags:
      - dotfiles

  - name: Install Apps
    homebrew_cask:
      pkg: "{{ item }}"
      state: present
      accept_external_apps: yes
    with_items:
      - karabiner-elements
      - firefox
      - bettertouchtool
      - iterm2
    tags:
      - apps
  - name: Install 1password 6
    shell: brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/fda3b24db9052dcbffa84e40138e355e88343dab/Casks/1password.rb
    changed_when: False
    tags:
      - apps

  - name: Setup Shell
    include: ./ansible/shell.yml
    tags:
      - shell

  - name: Setup Asthetics
    include: ./ansible/asthetics.yml
    tags:
      - asthetics

  - name: Install Window Manager
    include: ./ansible/window_manager.yml
    tags:
      - window_manager

  - name: Install Utilities
    include: ./ansible/utilities.yml
    tags:
      - utilities

  - name: Mackup Restore
    include: ./ansible/mackup.yml
    tags:
      - mackup
