- hosts: localhost
  become: true
  become_user: "{{ username }}"
  tasks:
  - name: Install Dotfiles
    include: ./ansible/dotfiles.yml
    tags:
      - dotfiles

  - name: Install Asthetics
    include: ./ansible/asthetics.yml
    tags:
      - asthetics

  - name: Install Window Manager
    include: ./ansible/window_manager.yml
    tags:
      - window_manager

  - name: Install Utilities
    include: ./ansible/utilities.yml
    tags:
      - utilities

  - name: Install Apps
    homebrew_cask:
      pkg: "{{ item }}"
      state: present
    ignore_errors: True
    with_items:
      - google-chrome
      - atom
      - anki
      - steam
      - discord
      - 1password
      - karabiner-elements
      - flux
      - deluge

  - name: Mackup Restore
    include: ./ansible/mackup.yml
    tags:
      - mackup
