- hosts: localhost
  become: true
  become_user: kevintpeng
  tasks:
  # LINK DOTFILES
  - name: link .vimrc
    shell: ln .vimrc ~/.vimrc
    ignore_errors: yes
    register: command_result
    changed_when: command_result.stderr == ""
  - name: link .tmux.conf
    shell: ln .tmux.conf ~/.tmux.conf
    ignore_errors: yes
    register: command_result
    changed_when: command_result.stderr == ""
  - name: link .chunkwmrc
    shell: ln .chunkwmrc ~/.chunkwmrc
    ignore_errors: yes
    register: command_result
    changed_when: command_result.stderr == ""
  - name: link .skhdrc
    shell: ln .skhdrc ~/.skhdrc
    ignore_errors: yes
    register: command_result
    changed_when: command_result.stderr == ""
  - name: link .zshrc
    shell: ln .zshrc ~/.zshrc
    ignore_errors: yes
    register: command_result
    changed_when: command_result.stderr == ""

  # UTILITIES
  - name: Install tree
    homebrew:
      name: tree
      state: present
  - name: Install fzf
    homebrew:
      name: fzf
      state: present
  - name: Configure fzf with useful key bindings and fuzzy completion
    shell: $(brew --prefix)/opt/fzf/install
  - name: Install tmux
    homebrew:
      name: tmux
      state: present
  - name: Install iTerm2
    homebrew_cask:
      pkg: iterm2
      state: present
  - name: Install vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim
      update: yes
  - name: Install all vim plugins
    shell: vim +PluginInstall +qall

  # ASTHETIC
  #- name: Tap Hack Nerd Font
  #  homebrew_tap:
  #    name: caskroom/fonts
  #    state: present
  - name: install hack-nerd-font
    homebrew_cask:
      pkg: font-hack-nerd-font
      state: present

  # WINDOW MANAGER
  - name: Tap chunkwm 
    homebrew_tap:
      name: crisidev/homebrew-chunkwm
      state: present
  - name: Install chunkwm
    homebrew:
      name: chunkwm
      state: present
  - name: Install skhd
    homebrew:
      pkg: koekeishiya/formulae/skhd
      state: present
      options: HEAD,with-logging
  - name: Install chunkwm
    homebrew_cask:
      pkg: chunkwm
      state: present

